### ISSUE TITLE
activemq centos 测试端口无法访问 重新在阿里上-t测试端口可以正常访问

### ISSUE THREAD

**Issue by tangi07** [Websoft9/ansible-activemq#4]
**Describe the bug**

![{RN7X$%`J1~KW9AS997T(G0](https://user-images.githubusercontent.com/92657958/156091157-b0b29b41-75d9-4ff1-893b-535eaee1fbde.png)

![QQ截图20220302105918](https://user-images.githubusercontent.com/100544684/156287107-3db95113-f336-4017-8b6b-42928001fcb8.png)

## Deployment method

- [x] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [x] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [ ] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
(paste here) 

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot

paste screenshot here

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/156115466-76d9c620-fb9e-4bbc-b2a2-041f7c9e273f.png)

**Comment by qiaofeng1227** [comment]
1. ansible中修改hostname
2. mcloud修改名称，对create_vm设定名称去掉.? 其他规则？
